CREATE TABLE usuario
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_formas_pagamento
(
    usuario_id       BIGINT  NOT NULL,
    formas_pagamento VARCHAR NOT NULL
);


ALTER TABLE usuario_formas_pagamento
    ADD CONSTRAINT fk_usuario_formaspagamento_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);